### ISSUE TITLE
Feature Request: Extend the Generator to Work with CRD

### ISSUE THREAD

**Issue by inoc603** [apple/pkl-k8s#3]
The current generation process for built-in k8s object are very nice. It would be great if it was extended to handle generating pkl package for CRDs as well.

For example:

```
kubectl get crds some-crd -o yaml | pkl-k8s-generate -o output_dir
```

**Comment by stackoverflow** [comment]
There's a CRD package here: https://github.com/apple/pkl-pantry/tree/main/packages/k8s.contrib.crd
Is this what you are looking for?

**Comment by inoc603** [comment]
Oh yes exactly! Never realize that the generator can be written in pkl as well. Very cool. Thanks!
